# https://docs.github.com/en/actions

name: âš™ğŸ¤–

on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize]

  schedule:
    - cron: 0 6 * * 1 # Every Monday at 1:00PM (GMT+7) or every Monday at 6:00AM (UTC)

jobs:
  test_install:
    name: âš™ Test Install ğŸ› 

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: ğŸ§¹ Clean up
        run: echo 'TODO'
      #   run: |
      #     bash -c "$(curl -fsLS https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force --quiet
      #     sudo rm -f /usr/local/bin/node
      #     sudo rm -f /usr/local/bin/yarn

      # - name: ğŸ›ï¸ Checkout
      #   uses: actions/checkout@v2.4.0
      #   with:
      #     submodules: "recursive"

      # - name: âœ¨ Initial Install
      #   run: |
      #     bash -c ./install.sh

      # - name: ğŸ§ª Run Tests
      #   env:
      #     ZSH_DISABLE_COMPFIX: true
      #   run: |
      #     source ~/.zshrc
      #     bootstrap
      #   shell: zsh {0}
