# https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# Workflows commands (::set-output, etc): # https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter

name: CI âš™ğŸ¤–

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  schedule:
    - cron: 0 22 * * 0 # Every Monday at 5:00AM (GMT+7) or every Sunday at 22:00PM (UTC)

jobs:
  test_install:
    name: Test Install âš™ğŸ› 

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clean up ğŸ§¹
        run: |
          bash -c "$(curl -fsLS https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- --force --quiet
          sudo rm -f /usr/local/bin/node
          sudo rm -f /usr/local/bin/yarn

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.4
        with:
          submodules: "recursive"

      - name: Initial Install âœ¨
        run: |
          bash -c ./install.sh

      - name: Run Tests ğŸ§ª
        env:
          ZSH_DISABLE_COMPFIX: true
        run: |
          source ~/.zshrc
          bootstrap
        shell: zsh {0}
